title = "Wandering Mushroom"
base_url = "https://confident-bhabha-f589dc.netlify.app/"
compile_sass = true

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

generate_feed = true

[slugify]
paths = "safe"

[extra]
anpu_date_format="%e %B %Y"
anpu_menu_links = [
    { url = "/", name = "Home" },
    { url = "/pages/about/", name = "About" },
    { url = "/tags/", name = "Tags" },
]