baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hollow Mushroom"
theme = "jane"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "Simon Bergot"

[taxonomies]
  category = "categories"

[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"