title = "Wandering Mushroom"
base_url = "https://example.com"
compile_sass = true

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

generate_feed = true

[slugify]
paths = "safe"

[extra]
anpu_date_format="%e %B %Y"
anpu_menu_links = [
    { url = "$BASE_URL/", name = "Home" },
    { url = "$BASE_URL/pages/about/", name = "About" },
    { url = "$BASE_URL/tags/", name = "Tags" },
]